### PR TITLE
Fix support annotations version

### LINKED ISSUE #6: Support Annotations version references non-existant value
If you look at  https://github.com/schlan/picassocompat/blob/80d5e5e1de5ff72bac36cc0ce3754660ccf595e4/picassocompat/build.gradle#L30

It references `versions.supportLibVersion` which is not defined

It should reference `versions.annotations`

### PR DESCRIPTION
**Pull request by jackmalpo**
Closes https://github.com/schlan/picassocompat/issues/6

### CODE REVIEW

**Comment by jackmalpo** [comment]
@schlan any chance we could merge this soon?

**Comment by schlan** [comment]
Sorry for delay, I was without a computer for a while. I'll try to get out a release out today.

**Comment by schlan** [comment]
Thanks for the PR!

**Comment by jackmalpo** [comment]
Awesome! Understand. Yeah a release today would be awesome :)

**Pull request merged**
